### ISSUE TITLE
Error occurred while launching mavros 

### ISSUE THREAD

**Issue by yhdurkaya** [ctu-mrs/mrs_simulation#22]
Hello folks, 
Thanks for the good work you've done over here. My problem is that whenever I try to create a drone, mavros throws some error that I don't know about. 
![Screenshot from 2022-04-27 17-55-26](https://user-images.githubusercontent.com/47098320/165548072-ca67c826-b7a3-4b02-a939-df39314a3112.png)

This is the error part. I am guessing it has some problems about loading run_simulation_mavros.launch(what a genius, am I right?) but I couldn't debug the launch file. Anyone knows what is this about? I checked logs but there is no information about the error, it just says that the error occured while launching mavros.

**Comment by klaxalk** [comment]
Hey, firstly thanks! Could you please provide more text output of this terminal tab? Moreover, some traditional questions:
- do you have an up-to-date system?
- what session are you launching, what UAV?
If you "just use" our system, I recommend trying our new singularity pipeline: https://github.com/ctu-mrs/mrs_singularity/

**Comment by yhdurkaya** [comment]
I have an Ubuntu 18.04 system and I installed PX4 and ROS(melodic) via the script that is shared in PX4 page. 
I use "roslaunch mrs_simulation simulation.launch" and "rosservice call /mrs_drone_spawner/spawn "1 --f550 --enable-realsense-front-pitched"" to work it out. First one works fine but when I run the second one, the terminal that runs gazebo and stuff gets errors.

![mavros](https://user-images.githubusercontent.com/47098320/165699710-c3441a08-3ad6-41ea-b62c-2b837e35ed16.png)

**Comment by stibipet** [comment]
Hello,
this problem is usually linked with a _zombie_ process running in the background from a previous simulation. Please check that there is no process called "px4" and "mavros_node" running before launching a new simulation (`killall px4 mavros_node` should handle those). If you use tmux and have the MRS linux setup installed as well, there is a key shortcut to cleanly dispose of all the terminal groups: press `ctrl + a` then **release**, and then press `k`.

Also, make sure to assign unique IDs to the drones, if you call the spawner multiple times. This is the first number argument you pass into the spawning script. You can also try spawning two drones at once: `rosservice call /mrs_drone_spawner/spawn "1 2 --f550 --enable-realsense-front-pitched"`

**Comment by yhdurkaya** [comment]
Thanks for your information but I tried and the problem is not about that. It doesn't even work on my first try. I checked the processes and tried to kill all processes related to px4 and mavros but there was none. Could there be anything else that causes this?

**Comment by stibipet** [comment]
From your previous post:

`I have an Ubuntu 18.04 system and I installed PX4 and ROS(melodic) via the script that is shared in PX4 page.`

Are you using the [px4_firmware](https://github.com/ctu-mrs/px4_firmware) from **ctu-mrs repositories**? It should be installed as a part of the [MRS UAV System](https://github.com/ctu-mrs/mrs_uav_system), with no additional steps required.
If you installed PX4 from the official repos, it will not be compatible with our setup, which might be the cause for mavros not connecting properly.

**Comment by yhdurkaya** [comment]
Oh this might be the problem, I didn't know that. 
I will install it with MRS UAV System and check if it works. 

Thanks for the help.

**Comment by klaxalk** [comment]
@yhdurkaya https://github.com/ctu-mrs/mrs_singularity/

**Comment by yhdurkaya** [comment]
I built singularity but there is a problem. https://github.com/ctu-mrs/mrs_singularity/issues/2 like this one, gazebo doesn't show up and I am sure that I have Nvidia Graphics. Could there be any other reason behind this problem?

**Comment by yhdurkaya** [comment]
The latest issue that I mentioned on my previous comment is solved under this https://github.com/ctu-mrs/mrs_singularity/issues/2.
