### ISSUE TITLE
Add uvleds and uvcam on x500 model

### ISSUE THREAD

**Issue by spurnvoj** [ctu-mrs/mrs_simulation#29]
* @DanHert create 3d models for holders
* @ViktorWalter add cameras and leds into the model

**Comment by DanHert** [comment]
Hello, added the LEDs, Cameras (left right and back) and Beacon to the X500 in commit [54dcd22](https://github.com/ctu-mrs/mrs_simulation/commit/54dcd2244ea7f729090f28d1524d2a757b4d5fa6)
I also fixed the beacon on the F450.

@ViktorWalter please check that the UVDAR works properly with the F450 and X500.

**Comment by spurnvoj** [comment]
@DanHert Please don't push not tested parts directly to the master branch. Do the PR for it and wait until somebody else confirms the right functionality.

**Comment by spurnvoj** [comment]
For example, you push there by mistake wrong characters https://github.com/ctu-mrs/mrs_simulation/commit/54dcd2244ea7f729090f28d1524d2a757b4d5fa6#diff-feb21223b8a392c8eb325cd46d024b7b07527f2722adf3beab94b12e59506ce9R1410

**Comment by ViktorWalter** [comment]
Fixed
