### ISSUE TITLE
Realsense Pointcloud

### ISSUE THREAD

**Issue by dringakn** [ctu-mrs/mrs_simulation#9]
Hi,
Thanks for sharing this wonderful package!
I have one question regarding the real-sense camera.
How does the real-sense camera outputs a pointcloud2 message?
Regards,
Ahmad

**Comment by spurnvoj** [comment]
Hi,
our real-sense plugin publishes currently just depth image. If you want to have pointcloud2 msg, launch this launch file:
```xml
<launch>
  <arg name="uav_name" default="$(env UAV_NAME)"/>
  <arg name="n_threads" default="8" />

  <group ns="$(arg uav_name)">
    <!-- Nodelet manager -->
    <node pkg="nodelet" type="nodelet" name="realsense_nodelet_manager" args="manager" output="screen">
      <param name="num_worker_threads" value="$(arg n_threads)" />
    </node>

    <node pkg="nodelet" type="nodelet" name="points_xyz" args="load depth_image_proc/point_cloud_xyz realsense_nodelet_manager">
      <remap from="image_rect" to="rs_d435/aligned_depth_to_color/image_raw" />
      <remap from="camera_info" to="rs_d435/aligned_depth_to_color/camera_info" />
      <remap from="points" to="rs_d435/depth/points" />
    </node>
  </group>
</launch>

```

**Comment by dringakn** [comment]
Thanks for the quick answer!

**Comment by ZhiWei20011** [comment]
Hi, may I know how to launch the above file? Like where to launch?

**Comment by dringakn** [comment]
> Hi, may I know how to launch the above file? Like where to launch?

what do you mean?

**Comment by ZhiWei20011** [comment]
> Hi,
> our real-sense plugin publishes currently just depth image. If you want to have pointcloud2 msg, launch this launch file:
> 
> ```
> <launch>
>   <arg name="uav_name" default="$(env UAV_NAME)"/>
>   <arg name="n_threads" default="8" />
> 
>   <group ns="$(arg uav_name)">
>     
>     <node pkg="nodelet" type="nodelet" name="realsense_nodelet_manager" args="manager" output="screen">
>       <param name="num_worker_threads" value="$(arg n_threads)" />
>     </node>
> 
>     <node pkg="nodelet" type="nodelet" name="points_xyz" args="load depth_image_proc/point_cloud_xyz realsense_nodelet_manager">
>       <remap from="image_rect" to="rs_d435/aligned_depth_to_color/image_raw" />
>       <remap from="camera_info" to="rs_d435/aligned_depth_to_color/camera_info" />
>       <remap from="points" to="rs_d435/depth/points" />
>     </node>
>   </group>
> </launch>
> ```
Where do I see the pointcloud2 msg after enabling the realsense-front camera

**Comment by dringakn** [comment]
you could list/echo the rostopic or view within rviz.

**Comment by ZhiWei20011** [comment]
How do I list the rostopic? Able to guide step by step? I am fairly new to ROS

**Comment by ZhiWei20011** [comment]
Or how to view within rviz

**Comment by dringakn** [comment]
http://wiki.ros.org/rviz/Tutorials

**Comment by ZhiWei20011** [comment]
Is it under the video tutorial
